# Golang CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: narwhalpillar/dart-phantom

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /app
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: pub get
      - run: pub get --offline
      - run: pub serve & sleep 3 && pub run test --pub-serve=8081 -p phantomjs
      #- run: pub run test -p phantomjs